"use client";

import { useState } from "react";
import { usePlanStore } from "@/stores/plan-store";
import { Button } from "@/components/ui/button";
import { FileDown, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { formatSalaryRange } from "@/lib/utils";
import { CAREER_CATEGORIES, PATHWAY_TYPES } from "@/lib/constants";
import type { CareerCategory } from "@prisma/client";

// ── Color helpers ──

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

const CATEGORY_RGB: Record<CareerCategory, [number, number, number]> = {
  TECHNOLOGY: [59, 130, 246],
  HEALTH: [244, 63, 94],
  TRADES: [249, 115, 22],
  CREATIVE: [168, 85, 247],
  BUSINESS: [16, 185, 129],
  EDUCATION: [6, 182, 212],
  SCIENCE: [99, 102, 241],
  SPORTS: [132, 204, 22],
  SERVICES: [245, 158, 11],
};

const STEP_TYPE_COLORS: Record<string, [number, number, number]> = {
  school: [59, 130, 246],
  transition: [245, 158, 11],
  study: [16, 185, 129],
  work: [99, 102, 241],
};

const STEP_TYPE_LABELS: Record<string, string> = {
  school: "School",
  transition: "Transition",
  study: "Study",
  work: "Work",
};

// ── Image loader ──

async function loadImageAsBase64(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export function PdfButton() {
  const [loading, setLoading] = useState(false);
  const { title, careers, timeline } = usePlanStore();

  const handleDownload = async () => {
    if (careers.length === 0) {
      toast.error("Add careers to your plan before exporting.");
      return;
    }

    setLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - margin * 2;
      let y = 0;

      // ── Drawing helpers ──

      const checkPage = (needed: number): boolean => {
        if (y + needed > pageHeight - 20) {
          drawFooter();
          doc.addPage();
          y = margin;
          return true;
        }
        return false;
      };

      const drawRoundedRect = (
        x: number,
        ry: number,
        w: number,
        h: number,
        r: number,
        fillColor: [number, number, number],
        strokeColor?: [number, number, number]
      ) => {
        doc.setFillColor(...fillColor);
        if (strokeColor) {
          doc.setDrawColor(...strokeColor);
          doc.setLineWidth(0.3);
          doc.roundedRect(x, ry, w, h, r, r, "FD");
        } else {
          doc.roundedRect(x, ry, w, h, r, r, "F");
        }
      };

      const drawPill = (
        x: number,
        py: number,
        text: string,
        bgColor: [number, number, number],
        textColor: [number, number, number]
      ): number => {
        doc.setFontSize(7);
        const textW = doc.getTextWidth(text);
        const pillW = textW + 4;
        const pillH = 4.5;
        drawRoundedRect(x, py - 3.2, pillW, pillH, 2, bgColor);
        doc.setTextColor(...textColor);
        doc.setFont("helvetica", "normal");
        doc.text(text, x + 2, py);
        return pillW + 2;
      };

      let currentPage = 1;

      const drawFooter = () => {
        doc.setDrawColor(200, 210, 225);
        doc.setLineWidth(0.3);
        doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(148, 163, 184);
        doc.text(
          "Generated by CareerIgnite  |  Career data is indicative only — verify requirements with institutions.",
          pageWidth / 2,
          pageHeight - 9.5,
          { align: "center" }
        );
        doc.text(`Page ${currentPage}`, pageWidth - margin, pageHeight - 9.5, {
          align: "right",
        });
        currentPage++;
      };

      // ── Preload images ──

      const careerImages: Record<string, string> = {};
      const imagePromises = careers.map(async (entry) => {
        const slug = entry.career.slug;
        const dataUrl = await loadImageAsBase64(`/images/careers/${slug}.png`);
        if (dataUrl) careerImages[slug] = dataUrl;
      });
      await Promise.all(imagePromises);

      // ══════════════════════════════════════════
      // 1. HEADER (gradient background, ~55mm)
      // ══════════════════════════════════════════

      const headerH = 55;
      // Smooth gradient: thin vertical slices from blue-600 → teal-600
      const slices = 40;
      const sliceW = pageWidth / slices;
      const startRgb = [37, 99, 235]; // blue-600
      const endRgb = [13, 148, 136];  // teal-600
      for (let s = 0; s < slices; s++) {
        const t = s / (slices - 1);
        doc.setFillColor(
          Math.round(startRgb[0] + (endRgb[0] - startRgb[0]) * t),
          Math.round(startRgb[1] + (endRgb[1] - startRgb[1]) * t),
          Math.round(startRgb[2] + (endRgb[2] - startRgb[2]) * t)
        );
        doc.rect(s * sliceW, 0, sliceW + 0.5, headerH, "F");
      }

      // Title text
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(28);
      doc.setFont("helvetica", "bold");
      doc.text("CareerIgnite", margin + 2, 22);

      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      const planTitle = title || "My Career Plan";
      doc.text(planTitle, margin + 2, 32);

      // Meta info (right side)
      doc.setFontSize(9);
      doc.setTextColor(200, 230, 255);
      doc.text(
        new Date().toLocaleDateString("en-AU", {
          day: "numeric",
          month: "long",
          year: "numeric",
        }),
        margin + 2,
        42
      );
      doc.text(
        `${careers.length} career${careers.length !== 1 ? "s" : ""} selected`,
        margin + 2,
        48
      );

      y = headerH + 10;

      // ══════════════════════════════════════════
      // 2. CAREER SUMMARY CARDS
      // ══════════════════════════════════════════

      // Section header
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(15, 23, 42);
      doc.text("Selected Careers", margin, y);
      y += 2;
      doc.setDrawColor(37, 99, 235);
      doc.setLineWidth(0.8);
      doc.line(margin, y, margin + 32, y);
      y += 8;

      for (let i = 0; i < careers.length; i++) {
        const entry = careers[i];
        const career = entry.career;
        const cat = career.category;
        const catInfo = CAREER_CATEGORIES[cat];
        const catRgb = CATEGORY_RGB[cat] || [59, 130, 246];
        const pathwayLabel =
          PATHWAY_TYPES[entry.selectedPathway]?.label || entry.selectedPathway;

        // Estimate card height
        const descLines = career.description
          ? doc.splitTextToSize(career.description, contentWidth - 42)
          : [];
        const descShown = descLines.slice(0, 2);
        const hasImage = !!careerImages[career.slug];
        const skillCount = Math.min(career.skills.length, 6);
        const skillRowH = skillCount > 0 ? 8 : 0;
        const cardH = Math.max(
          24 + descShown.length * 3.8 + skillRowH + 4,
          hasImage ? 38 : 28
        );

        checkPage(cardH + 6);

        const cardY = y;

        // Card background
        drawRoundedRect(
          margin,
          cardY,
          contentWidth,
          cardH,
          2.5,
          [248, 250, 252],
          [226, 232, 240]
        );

        // Left accent stripe
        doc.setFillColor(...catRgb);
        doc.roundedRect(margin, cardY, 3, cardH, 1.5, 1.5, "F");

        // Career image thumbnail (right side)
        const textRightBound = hasImage ? contentWidth - 32 : contentWidth - 4;
        if (hasImage) {
          try {
            doc.addImage(
              careerImages[career.slug],
              "PNG",
              margin + contentWidth - 28,
              cardY + 3,
              25,
              cardH - 6,
              undefined,
              "FAST"
            );
          } catch {
            // Skip image on error
          }
        }

        // Career title
        let cx = margin + 7;
        let cy = cardY + 6;
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text(career.title, cx, cy);

        // Category badge
        const badgeX = cx + doc.getTextWidth(career.title) + 3;
        if (badgeX + 20 < margin + textRightBound) {
          const catLabelRgb = catRgb;
          const bgTint: [number, number, number] = [
            Math.min(255, catRgb[0] + 180),
            Math.min(255, catRgb[1] + 180),
            Math.min(255, catRgb[2] + 180),
          ];
          drawPill(badgeX, cy, catInfo.label, bgTint, catLabelRgb);
        }

        cy += 5.5;

        // Salary, growth, pathway
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(71, 85, 105);
        const salary = formatSalaryRange(career.salaryLow, career.salaryHigh);
        const growth =
          career.growthRate > 0
            ? `+${career.growthRate}%`
            : `${career.growthRate}%`;
        const metaText = `${salary}  |  Growth: ${growth}  |  ${pathwayLabel}`;
        doc.text(metaText, cx, cy);
        cy += 4.5;

        // Description
        if (descShown.length > 0) {
          doc.setFontSize(7.5);
          doc.setTextColor(100, 116, 139);
          for (const line of descShown) {
            doc.text(line, cx, cy);
            cy += 3.8;
          }
          cy += 1;
        }

        // Skills pills
        if (career.skills.length > 0) {
          let pillX = cx;
          const pillY = cy + 1;
          const skills = career.skills.slice(0, 6);
          doc.setFontSize(6.5);
          for (const skill of skills) {
            const tw = doc.getTextWidth(skill) + 4;
            if (pillX + tw > margin + textRightBound) break;
            drawPill(
              pillX,
              pillY,
              skill,
              [228, 234, 245],
              [51, 65, 85]
            );
            pillX += tw + 2;
          }
        }

        y = cardY + cardH + 5;
      }

      y += 5;

      // ══════════════════════════════════════════
      // 3. TIMELINE SECTION
      // ══════════════════════════════════════════

      if (timeline.length > 0) {
        checkPage(25);

        // Section header
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text("Your Pathway Timeline", margin, y);
        y += 2;
        doc.setDrawColor(8, 145, 178);
        doc.setLineWidth(0.8);
        doc.line(margin, y, margin + 38, y);
        y += 10;

        const lineX = margin + 6;
        const cardX = margin + 16;
        const cardW = contentWidth - 18;

        for (let si = 0; si < timeline.length; si++) {
          const step = timeline[si];
          const stepColor = STEP_TYPE_COLORS[step.type] || [37, 99, 235];
          const typeLabel = STEP_TYPE_LABELS[step.type] || step.type;

          // Estimate height
          const stepDescLines = step.description
            ? doc.splitTextToSize(step.description, cardW - 8)
            : [];
          const detailCount = step.details?.length || 0;
          let detailTotalLines = 0;
          const detailLineArrays: string[][] = [];
          if (step.details) {
            for (const d of step.details) {
              const lines = doc.splitTextToSize(`• ${d}`, cardW - 12);
              detailLineArrays.push(lines);
              detailTotalLines += lines.length;
            }
          }
          const stepCardH =
            14 +
            stepDescLines.length * 3.5 +
            detailTotalLines * 3.5 +
            (detailCount > 0 ? 3 : 0) +
            4;

          checkPage(stepCardH + 4);

          const stepCardY = y;

          // Vertical connector line
          if (si < timeline.length - 1) {
            // Gradient simulated: top blue, bottom teal
            const halfH = stepCardH / 2;
            doc.setDrawColor(59, 130, 246);
            doc.setLineWidth(1.2);
            doc.line(lineX, stepCardY + 5, lineX, stepCardY + halfH);
            doc.setDrawColor(8, 145, 178);
            doc.line(
              lineX,
              stepCardY + halfH,
              lineX,
              stepCardY + stepCardH + 4
            );
          }

          // Circle on the line
          doc.setFillColor(...stepColor);
          doc.circle(lineX, stepCardY + 2, 3, "F");
          // White inner circle
          doc.setFillColor(255, 255, 255);
          doc.circle(lineX, stepCardY + 2, 1.5, "F");
          doc.setFillColor(...stepColor);
          doc.circle(lineX, stepCardY + 2, 0.8, "F");

          // Alternating card tint
          const tintBg: [number, number, number] =
            si % 2 === 0 ? [248, 250, 252] : [241, 245, 249];
          drawRoundedRect(
            cardX,
            stepCardY - 2,
            cardW,
            stepCardH,
            2,
            tintBg,
            [226, 232, 240]
          );

          // Year badge + type badge
          let bx = cardX + 4;
          const by = stepCardY + 4;

          // Year pill
          const yearPillW = drawPill(bx, by, step.year, stepColor, [
            255, 255, 255,
          ]);
          bx += yearPillW + 1;

          // Type label pill
          const typeBgTint: [number, number, number] = [
            Math.min(255, stepColor[0] + 190),
            Math.min(255, stepColor[1] + 190),
            Math.min(255, stepColor[2] + 190),
          ];
          drawPill(bx, by, typeLabel, typeBgTint, stepColor);

          // Title
          let sy = by + 6;
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(15, 23, 42);
          doc.text(step.title, cardX + 4, sy);
          sy += 4.5;

          // Description
          if (stepDescLines.length > 0) {
            doc.setFontSize(8);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(71, 85, 105);
            for (const line of stepDescLines) {
              doc.text(line, cardX + 4, sy);
              sy += 3.5;
            }
            sy += 1;
          }

          // Details
          if (detailLineArrays.length > 0) {
            doc.setFontSize(7.5);
            doc.setTextColor(100, 116, 139);
            for (const lines of detailLineArrays) {
              for (const dl of lines) {
                doc.text(dl, cardX + 6, sy);
                sy += 3.5;
              }
            }
          }

          y = stepCardY + stepCardH + 4;
        }
      }

      // ── Final footer pass on all pages ──

      drawFooter(); // footer for current (last) page

      // Re-stamp page numbers on all pages
      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        // Footer line
        doc.setDrawColor(200, 210, 225);
        doc.setLineWidth(0.3);
        doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
        // Footer text
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(148, 163, 184);
        doc.text(
          "Generated by CareerIgnite  |  Career data is indicative only — verify requirements with institutions.",
          pageWidth / 2,
          pageHeight - 9.5,
          { align: "center" }
        );
        doc.text(
          `Page ${p} of ${totalPages}`,
          pageWidth - margin,
          pageHeight - 9.5,
          { align: "right" }
        );
      }

      doc.save("career-plan.pdf");
      toast.success("PDF downloaded!");
    } catch (error) {
      console.error("PDF generation error:", error);
      toast.error("Failed to generate PDF. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button
      variant="outline"
      onClick={handleDownload}
      disabled={loading || careers.length === 0}
      className="gap-2 rounded-xl bg-card"
      size="sm"
    >
      {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileDown className="h-4 w-4" />}
      <span className="hidden sm:inline">Export PDF</span>
      <span className="sm:hidden">PDF</span>
    </Button>
  );
}
